export var COMMON_ERROR = 'COMMON_ERROR';
export var NOT_AUTHORIZED_ERROR = 'NOT_AUTHORIZED_ERROR';
export var NOT_FOUND_ERROR = 'NOT_FOUND_ERROR';
export var SERVER_ERROR = 'SERVER_ERROR';
export var VALIDATION_ERROR = 'VALIDATION_ERROR';
export var WRONG_RESPONSE_ERROR = 'WRONG_RESPONSE_ERROR';
//# sourceMappingURL=index.js.map